/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.pavel.common.enumiration;


/**
 * enum формы обучения
 */
public enum FormOfTraining {
  платная(1, ConstForEnums.PAID),
  бесплатная(2, ConstForEnums.FREE);

  private final int value;
  private String name;

  FormOfTraining(int value, String name) {
    this.value = value;
    this.name = name;
  }

  /**
   * значение
   * @return значение
   */
  public int getValue() {
    return value;
  }

  /**
   * получение формы обучения по id 
   * @param id
   * @return имя
   */
  public static String getById(int id) {
    for(FormOfTraining form : FormOfTraining.values()) {
      if(id == form.getValue()) {
        return form.getName();
      }
    }
    return null;
  }

  /**
   * имя
   * @return имя
   */
  public String getName() {
    return name;
  }

}
