/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.pavel.common.enumiration;


/**
 * enum групп
 */
public enum GroupNumber {
  первая(1, ConstForEnums.FIRST),
  вторая(2,ConstForEnums.SECOND),
  третья(3, ConstForEnums.THIRD);

  private int value;
  private String group;

  GroupNumber(int value, String group) {
    this.value = value;
    this.group = group;
  }

  /**
   * значение
   * @return значение
   */
  public int getValue() {
    return value;
  }

  /**
   * получение группы по id
   * @param id
   * @return номер группы 
   */
  public static String getById(int id) {
    for(GroupNumber group : GroupNumber.values()) {
      if(id == group.getValue()) {
        return group.getGroup();
      }
    }
    return null;
  }

  public String getGroup() {
    return group;
  }

}
